T_b("package ");
T_b(self->package);
T_b(";");
T_b("\n");
T_b(imports);
T_b("\n");
T_b("public class ");
T_b(self->name);
T_b(" extends Template<");
T_b(self->comp_name);
T_b("> {");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(self->name);
T_b("( ");
T_b(self->comp_name);
T_b(" population ) {");
T_b("\n");
T_b("        ");
T_b("super( population );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public void evaluate() throws XtumlException {");
T_b("\n");
T_b(self->blob);
T_b("    }");
T_b("\n");
T_b("}");
T_b("\n");
