T_b("        ");
T_b("case \"");
T_b(self->name);
T_b("\":");
T_b("\n");
T_b("            ");
T_b("return new Template<");
T_b(self->comp_name);
T_b(">( population ) {");
T_b("\n");
T_b("                ");
T_b("@Override");
T_b("\n");
T_b("                ");
T_b("public void evaluate() throws XtumlException ");
T_b(body);
T_b("\n");
T_b("            ");
T_b("};");
T_b("\n");
