T_b("package ");
T_b(self->package);
T_b(";");
T_b("\n");
T_b("public enum ");
T_b(self->name);
T_b(" {");
T_b("\n");
T_b("    ");
T_b("UNINITIALIZED_ENUM( -1 )");
T_b(enumerators);
T_b("\n");
T_b("    ");
T_b("private final int value;");
T_b("\n");
T_b("    ");
T_b(self->name);
T_b("( int value ) {");
T_b("\n");
T_b("        ");
T_b("this.value = value;");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("public int getValue() {");
T_b("\n");
T_b("        ");
T_b("return value;");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("}");
T_b("\n");
