CREATE TABLE INT_WARN (
    BodyLabel STRING,
    LineNumber INTEGER,
    Message STRING
);
CREATE TABLE O_OIDI (
    Var_ID UNIQUE_ID,
    Attr_ID UNIQUE_ID,
    Obj_ID UNIQUE_ID,
    Oid_ID INTEGER,
    Block_ID UNIQUE_ID,
    initialized BOOLEAN
);
CREATE ROP REF_ID R199 FROM MC O_OIDI (Var_ID) TO 1 V_VAR (Var_ID);
CREATE ROP REF_ID R199 FROM MC O_OIDI (Attr_ID, Obj_ID, Oid_ID) TO 1 O_OIDA (Attr_ID, Obj_ID, Oid_ID);
CREATE ROP REF_ID R198 FROM MC O_OIDI (Block_ID) to 1 ACT_BLK (Block_ID);
