T_b("            ");
T_b("case \"");
T_b(self->msg_name);
T_b("\":");
T_b("\n");
T_b("                ");
T_b(self->msg_name);
T_b("(");
T_b(message_parameter_list);
T_b(");");
T_b("\n");
T_b("                ");
T_b("break;");
T_b("\n");
