T_b("package ");
T_b(package_name);
T_b(";");
T_b("\n");
T_b(import_block);
T_b("\n");
T_b("public class ");
T_b(port_name);
T_b(" extends ");
T_b(extends_class);
T_b(" implements ");
T_b(interface_name);
T_b(" {");
T_b("\n");
T_b("    ");
T_b("// inbound messages");
T_b("\n");
T_b(inbound_message_block);
T_b("\n");
T_b("    ");
T_b("// outbound messages");
T_b("\n");
T_b(outbound_message_block);
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public void receive( IMessage message ) {");
T_b("\n");
T_b("        ");
T_b("if ( null != message ) {");
T_b("\n");
T_b("            ");
T_b("switch ( message.getName() ) {");
T_b("\n");
T_b(message_switch_block);
T_b("\n");
T_b("                ");
T_b("default:");
T_b("\n");
T_b("                    ");
T_b("break;");
T_b("\n");
T_b("            ");
T_b("}");
T_b("\n");
T_b("        ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("}");
T_b("\n");
