T_b("package ");
T_b(self->package);
T_b(";");
T_b("\n");
T_b(imports);
T_b("\n");
T_b("public class ");
T_b(self->name);
T_b(" implements IApplication {");
T_b("\n");
T_b("    ");
T_b("IComponent<?>[] components;");
T_b("\n");
T_b("    ");
T_b("IRunContext[] executors;");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(self->name);
T_b("() {");
T_b("\n");
T_b("        ");
T_b("components = new IComponent<?>[");
T_b(T_s(num_component_instances));
T_b("];");
T_b("\n");
T_b("        ");
T_b("executors = new IRunContext[");
T_b(T_s(num_executors));
T_b("];");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public void setup() {");
T_b("\n");
T_b("        ");
T_b("for ( int i = 0; i < executors.length; i++ )");
T_b("\n");
T_b("            ");
T_b("executors[i] = new ApplicationExecutor( \"");
T_b(self->name);
T_b("Executor\" + i );");
T_b("\n");
T_b(component_instantiations);
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public void initialize() {");
T_b("\n");
T_b("        ");
T_b("for ( IComponent<?> component : components ) {");
T_b("\n");
T_b("            ");
T_b("component.getRunContext().execute( new GenericExecutionTask() {");
T_b("\n");
T_b("                ");
T_b("@Override");
T_b("\n");
T_b("                ");
T_b("public void run() throws XtumlException {");
T_b("\n");
T_b("                    ");
T_b("component.initialize();");
T_b("\n");
T_b("                ");
T_b("}");
T_b("\n");
T_b("            ");
T_b("});");
T_b("\n");
T_b("        ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public void start() {");
T_b("\n");
T_b("        ");
T_b("for ( IRunContext executor : executors ) {");
T_b("\n");
T_b("            ");
T_b("executor.start();");
T_b("\n");
T_b("        ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("public static void main( String[] args ) {");
T_b("\n");
T_b("        ");
T_b("IApplication app = new ");
T_b(self->name);
T_b("();");
T_b("\n");
T_b("        ");
T_b("app.setup();");
T_b("\n");
T_b("        ");
T_b("app.initialize();");
T_b("\n");
T_b("        ");
T_b("app.start();");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("}");
T_b("\n");
