T_b("    ");
T_b("public ");
T_b(type_name);
T_b(" get");
T_b(capital_name);
T_b("() throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("checkLiving();");
T_b("\n");
T_b("        ");
T_b("if ( this instanceof IEmptyInstance ) throw new EmptyInstanceException( \"Cannot get attribute of empty instance.\" );");
T_b("\n");
T_b(referential_getters);
T_b("\n");
T_b(attribute_processor);
T_b("\n");
T_b("        ");
T_b("return ");
T_b(name);
T_b(";");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("public void set");
T_b(capital_name);
T_b("( ");
T_b(type_name);
T_b(" ");
T_b(name);
T_b(" ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("checkLiving();");
T_b("\n");
T_b("        ");
T_b("if ( this instanceof IEmptyInstance ) throw new EmptyInstanceException( \"Cannot set attribute of empty instance.\" );");
T_b("\n");
T_b(referential_setters);
T_b("\n");
T_b("        ");
T_b("this.");
T_b(name);
T_b(" = ");
T_b(name);
T_b(";");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
