if ( is_getter ) {
T_b("    ");
T_b("public ");
T_b(type_name);
T_b(" get");
T_b(capital_name);
T_b("() throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("checkLiving();");
T_b("\n");
T_b("        ");
T_b("if ( this instanceof IEmptyInstance ) throw new EmptyInstanceException( \"Cannot get attribute of empty instance.\" );");
T_b("\n");
T_b(attribute_derivation);
T_b("\n");
T_b("        ");
T_b("return ");
T_b(self->attribute_name);
T_b(";");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
} else {
T_b("    ");
T_b("public void set");
T_b(capital_name);
T_b("( ");
T_b(type_name);
T_b(" ");
T_b(self->attribute_name);
T_b(" ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("checkLiving();");
T_b("\n");
T_b("        ");
T_b("if ( this instanceof IEmptyInstance ) throw new EmptyInstanceException( \"Cannot set attribute of empty instance.\" );");
T_b("\n");
if ( primitive ) {
T_b("        ");
T_b("if ( ");
T_b(self->attribute_name);
T_b(" != this.");
T_b(self->attribute_name);
T_b(" ) {");
T_b("\n");
} else {
T_b("        ");
T_b("if ( !");
T_b(self->attribute_name);
T_b(".equals( this.");
T_b(self->attribute_name);
T_b(" ) ) {");
T_b("\n");
}
T_b("            ");
T_b("this.");
T_b(self->attribute_name);
T_b(" = ");
T_b(self->attribute_name);
T_b(";");
T_b("\n");
T_b("            ");
T_b("/* TODO");
T_b("\n");
T_b(attribute_propagations);
T_b("");
T_b("            ");
T_b("*/");
T_b("\n");
T_b("        ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
}
