T_b("package ");
T_b(self->package);
T_b(";");
T_b("\n");
T_b(imports);
T_b("\n");
T_b("public interface ");
T_b(self->name);
T_b(" extends IModelInstance<");
T_b(self->name);
T_b(",");
T_b(self->comp_name);
T_b("> {");
T_b("\n");
T_b("    ");
T_b("// attributes");
T_b("\n");
T_b(attributes);
T_b("\n");
T_b("    ");
T_b("// operations");
T_b("\n");
T_b(operations);
T_b("\n");
T_b("    ");
T_b("// selections");
T_b("\n");
T_b(selectors);
T_b("\n");
T_b("}");
T_b("\n");
