T_b("package ");
T_b(self->package);
T_b(";");
T_b("\n");
T_b(imports);
T_b("\n");
T_b("import io.ciera.instanceloading.IInstanceLoader;");
T_b("\n");
T_b("import io.ciera.summit.exceptions.XtumlException;");
T_b("\n");
T_b("import java.io.OutputStream;");
T_b("\n");
T_b("import java.io.PrintStream;");
T_b("\n");
T_b("import java.util.List;");
T_b("\n");
T_b("public class ");
T_b(self->name);
T_b(" implements IInstanceLoader {");
T_b("\n");
T_b("    ");
T_b("private ");
T_b(self->comp_name);
T_b(" population;");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(self->name);
T_b("( ");
T_b(self->comp_name);
T_b(" population ) {");
T_b("\n");
T_b("        ");
T_b("this.population = population;");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("public void insert( String tableName, List<Object> values ) {");
T_b("\n");
T_b("        ");
T_b("System.out.println( tableName );");
T_b("\n");
T_b("        ");
T_b("for ( Object val : values ) System.out.println( \"  \" + val.toString() + \": \" + val.getClass().getName() );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("public void finish() {}");
T_b("\n");
T_b("    ");
T_b("public void serialize( OutputStream stream ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("PrintStream out = new PrintStream( stream );");
T_b("\n");
T_b(instance_serializers);
T_b("        out.flush();");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("}");
T_b("\n");
