T_b("package ");
T_b(self->package);
T_b(";");
T_b("\n");
T_b("import io.ciera.sql.util.IInstanceLoader;");
T_b("\n");
T_b("import java.util.List;");
T_b("\n");
T_b("public class ");
T_b(self->name);
T_b(" implements IInstanceLoader {");
T_b("\n");
T_b("    ");
T_b("public void insert( String tableName, List<Object> values ) {}");
T_b("\n");
T_b("    ");
T_b("public void finish() {}");
T_b("\n");
T_b("}");
T_b("\n");
