T_b("        ");
T_b("for ( ");
T_b(self->class_name);
T_b(" ");
T_b(T_l(self->class_name));
T_b("_inst : population.");
T_b(self->class_name);
T_b("_instances() ) serialize_");
T_b(self->class_name);
T_b("( ");
T_b(T_l(self->class_name));
T_b("_inst, out );");
T_b("\n");
