T_b("package ");
T_b(self->package);
T_b(";");
T_b("\n");
T_b(imports);
T_b("\n");
T_b("public class ");
T_b(self->name);
T_b(" implements IPopulationLoader {");
T_b("\n");
T_b("    ");
T_b("private ");
T_b(self->comp_name);
T_b(" population;");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(self->name);
T_b("( ");
T_b(self->comp_name);
T_b(" population ) {");
T_b("\n");
T_b("        ");
T_b("this.population = population;");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public void insert( String tableName, List<Object> values ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("switch ( tableName ) {");
T_b("\n");
T_b(instance_loaders);
T_b("        default:");
T_b("\n");
T_b("            ");
T_b("throw new XtumlException( \"Class not supported by this population.\" );");
T_b("\n");
T_b("        ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public void finish() throws XtumlException {");
T_b("\n");
T_b(batch_relators);
T_b("    }");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public void serialize( OutputStream stream ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("PrintStream out = new PrintStream( stream );");
T_b("\n");
T_b(instance_serializers);
T_b("        out.flush();");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("}");
T_b("\n");
