T_b("    ");
T_b("public static class CLASS extends ActionHome<");
T_b(self->comp_name);
T_b("> {");
T_b("\n");
T_b("        ");
T_b("public CLASS( ");
T_b(self->comp_name);
T_b(" context ) {");
T_b("\n");
T_b("            ");
T_b("super( context );");
T_b("\n");
T_b("        ");
T_b("}");
T_b("\n");
T_b(operations);
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
