T_b("package ");
T_b(package_name);
T_b(";");
T_b("\n");
T_b(import_block);
T_b("\n");
T_b("public class ");
T_b(application_name);
T_b(" extends XtumlApplication {");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public void setup() {");
T_b("\n");
T_b("        ");
T_b("// set the number of threads in the system");
T_b("\n");
T_b("        ");
T_b("setNumberThreads( ");
T_b(num_threads);
T_b(" );");
T_b("\n");
T_b("        ");
T_b("// create components");
T_b("\n");
T_b("        ");
T_b("setComponents( new Component[]{ ");
T_b(component_block);
T_b(" } );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("public static void main( String[] args ) {");
T_b("\n");
T_b("        ");
T_b("XtumlApplication.app = new ");
T_b(application_name);
T_b("();");
T_b("\n");
T_b("        ");
T_b("XtumlApplication.app.setup();");
T_b("\n");
T_b("        ");
T_b("XtumlApplication.app.initialize();");
T_b("\n");
T_b("        ");
T_b("XtumlApplication.app.start();");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("}");
T_b("\n");
