T_b("package ");
T_b(package);
T_b(";");
T_b("\n");
T_b(imports);
T_b("\n");
T_b("public class ");
T_b(name);
T_b(" extends ");
T_b(extends);
T_b(" {");
T_b("\n");
T_b("   ");
T_b(" ");
T_b("\n");
T_b("    ");
T_b("private static final String keyLetters = \"");
T_b(key_letters);
T_b("\";");
T_b("\n");
T_b("    ");
T_b("// constructor");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(name);
T_b("( IInstancePopulation context ) {");
T_b("\n");
T_b("        ");
T_b("super( context );");
T_b("\n");
T_b(attribute_initializers);
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("   ");
T_b(" ");
T_b("\n");
T_b("    ");
T_b("// attributes");
T_b("\n");
T_b(attributes);
T_b("\n");
T_b("    ");
T_b("// operations");
T_b("\n");
T_b(operations);
T_b("\n");
T_b("   ");
T_b(" ");
T_b("\n");
T_b("    ");
T_b("// selections");
T_b("\n");
T_b(selectors);
T_b("\n");
T_b("    ");
T_b("// empty instance");
T_b("\n");
T_b("    ");
T_b("public static final ");
T_b(name);
T_b(" empty");
T_b(name);
T_b(" = new Empty");
T_b(name);
T_b("();");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public String getKeyLetters() {");
T_b("\n");
T_b("        ");
T_b("return keyLetters;");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public IInstanceSet toSet() {");
T_b("\n");
T_b("        ");
T_b("IInstanceSet set = new ");
T_b(class_set_name);
T_b("();");
T_b("\n");
T_b("        ");
T_b("set.add( this );");
T_b("\n");
T_b("        ");
T_b("return set;");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("}");
T_b("\n");
T_b("class Empty");
T_b(name);
T_b(" extends ");
T_b(name);
T_b(" implements IEmptyInstance {");
T_b("\n");
T_b("   ");
T_b(" ");
T_b("\n");
T_b("    ");
T_b("public Empty");
T_b(name);
T_b("() {");
T_b("\n");
T_b("        ");
T_b("super( null );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("// selections");
T_b("\n");
T_b(empty_selectors);
T_b("\n");
T_b("}");
T_b("\n");
