T_b("package ");
T_b(package_name);
T_b(";");
T_b("\n");
T_b(import_block);
T_b("\n");
T_b("public class ");
T_b(component_name);
T_b(" extends Component {");
T_b("\n");
T_b("   ");
T_b(" ");
T_b("\n");
T_b("    ");
T_b("private static final Class<?>[] classes = new Class<?>[] {");
T_b("\n");
T_b("        ");
T_b(class_list);
T_b("\n");
T_b("    ");
T_b("};");
T_b("\n");
T_b("   ");
T_b(" ");
T_b("\n");
T_b("    ");
T_b("// selections");
T_b("\n");
T_b("    ");
T_b(select_from_instances_block);
T_b("\n");
T_b("    ");
T_b("// component initialization functions");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
if ( init_block_throws_exception ) {
T_b("    ");
T_b("public void initialize() throws XtumlException {");
T_b("\n");
} else {
T_b("    ");
T_b("public void initialize() {");
T_b("\n");
}
T_b("        ");
T_b(init_block);
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public Class<?>[] getClasses() {");
T_b("\n");
T_b("        ");
T_b("return classes;");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("}");
T_b("\n");
