T_b("package ");
T_b(package);
T_b(";");
T_b("\n");
T_b(imports);
T_b("\n");
T_b("public class ");
T_b(name);
T_b(" extends ");
T_b(extends);
T_b(" {");
T_b("\n");
T_b("   ");
T_b(" ");
T_b("\n");
T_b("    ");
T_b("private Map<String, Class<?>> classes;");
T_b("\n");
T_b("    ");
T_b("private Map<Integer, Class<?>> relationships;");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(name);
T_b("() {");
T_b("\n");
T_b("        ");
T_b("super(");
T_b(port_initializers);
T_b(");");
T_b("\n");
T_b("        ");
T_b("setClasses();");
T_b("\n");
T_b("        ");
T_b("setRelationships();");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("   ");
T_b(" ");
T_b("\n");
T_b("    ");
T_b("// selections");
T_b("\n");
T_b(selects);
T_b("\n");
T_b("    ");
T_b("// ports");
T_b("\n");
T_b(ports);
T_b("\n");
T_b("    ");
T_b("// component initialization function");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public void initialize() throws XtumlException {");
T_b("\n");
T_b(init);
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public Map<String, Class<?>> getClasses() {");
T_b("\n");
T_b("        ");
T_b("return classes;");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public Map<Integer, Class<?>> getRelationships() {");
T_b("\n");
T_b("        ");
T_b("return relationships;");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("private void setClasses() {");
T_b("\n");
T_b("        ");
T_b("classes = new HashMap<>();");
T_b("\n");
T_b(classes);
T_b("");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("private void setRelationships() {");
T_b("\n");
T_b("        ");
T_b("relationships = new HashMap<>();");
T_b("\n");
T_b(relationships);
T_b("");
T_b("    ");
T_b("}");
T_b("\n");
T_b("}");
T_b("\n");
