if ( is_many ) {
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(type_class_name);
T_b(" selectAny");
T_b(type_key_letters);
T_b("OnR");
T_b(rel_numb);
T_b(phrase);
T_b("( IWhere condition ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("return ");
T_b(type_class_name);
T_b(".empty");
T_b(type_class_name);
T_b(";");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(type_name);
T_b(" selectMany");
T_b(type_key_letters);
T_b("sOnR");
T_b(rel_numb);
T_b(phrase);
T_b("( IWhere condition ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("return new ");
T_b(type_name);
T_b("();");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
} else {
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(type_name);
T_b(" selectOne");
T_b(type_key_letters);
T_b("OnR");
T_b(rel_numb);
T_b(phrase);
T_b("( IWhere condition ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("return ");
T_b(type_name);
T_b(".empty");
T_b(type_name);
T_b(";");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
}
