T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public void unrelateFrom");
T_b(type_key_letters);
T_b("AcrossR");
T_b(rel_numb);
T_b(phrase);
T_b("( ");
T_b(type_name);
T_b(" ");
T_b(type_name);
T_b(" ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("throw new EmptyInstanceException( \"Unrelate of empty instance\" );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
