T_b("package ");
T_b(package_name);
T_b(";");
T_b("\n");
T_b(import_block);
T_b("\n");
T_b("public class ");
T_b(class_name);
T_b("InstanceStateMachine extends InstanceStateMachine {");
T_b("\n");
T_b("   ");
T_b(" ");
T_b("\n");
T_b("    ");
T_b(states_block);
T_b("\n");
T_b("    ");
T_b("private static final String[] stateNames = new String[] {");
T_b("\n");
T_b("        ");
T_b(state_names_block);
T_b("\n");
T_b("    ");
T_b("};");
T_b("\n");
T_b("   ");
T_b(" ");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(class_name);
T_b("InstanceStateMachine() {");
T_b("\n");
T_b("        ");
T_b("sem = new StateEventMatrix( new int[][]{");
T_b("\n");
T_b("            ");
T_b(state_rows);
T_b("\n");
T_b("        ");
T_b("}) {");
T_b("\n");
T_b("            ");
T_b("@Override");
T_b("\n");
T_b("            ");
T_b("public String getStateName( int state ) {");
T_b("\n");
T_b("                ");
T_b("return stateNames[state];");
T_b("\n");
T_b("            ");
T_b("}");
T_b("\n");
T_b("        ");
T_b("};");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public void stateActivity(int stateNum, Event e) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b(state_activity_switch_block);
T_b("\n");
T_b("        ");
T_b("else throw new StateMachineException( \"State does not exist.\" );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("   ");
T_b(" ");
T_b("\n");
T_b("    ");
T_b(state_activity_block);
T_b("\n");
T_b("}");
T_b("\n");
