T_b("    ");
T_b("public void set");
T_b(ref_name);
T_b("OnR");
T_b(rel_numb);
T_b("( ");
T_b(target_type_name);
T_b(" p_");
T_b(ref_name);
T_b(" ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("if ( !(");
T_b(ref_name);
T_b(" instanceof EmptyInstance) ) ");
T_b(ref_name);
T_b(" = p_");
T_b(ref_name);
T_b(";");
T_b("\n");
T_b("        ");
T_b("else throw new LinkException( \"Cannot link to already linked relationship.\" );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("public void clear");
T_b(ref_name);
T_b("OnR");
T_b(rel_numb);
T_b("() throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("if ( !(");
T_b(ref_name);
T_b(" instanceof EmptyInstance) ) ");
T_b(ref_name);
T_b(" = ");
T_b(target_type_name);
T_b(".empty");
T_b(target_type_name);
T_b(";");
T_b("\n");
T_b("        ");
T_b("else throw new LinkException( \"Cannot unlink non-linked relationship.\" );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
