T_b("    ");
T_b("public ");
T_b(class_name);
T_b(" selectAny");
T_b(class_key_letters);
T_b("FromInstances( Where condition ) {");
T_b("\n");
T_b("        ");
T_b("return (");
T_b(class_name);
T_b(")selectAny( condition );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("   ");
T_b(" ");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(class_set_name);
T_b(" selectMany");
T_b(class_key_letters);
T_b("sFromInstances( Where condition ) {");
T_b("\n");
T_b("        ");
T_b("return (");
T_b(class_set_name);
T_b(")selectMany( condition );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
