if ( is_many ) {
T_b("    ");
T_b("public ");
T_b(target_type_obj_name);
T_b(" selectAny");
T_b(type_key_letters);
T_b("OnR");
T_b(rel_numb);
T_b(phrase);
T_b("() throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("return selectAny");
T_b(type_key_letters);
T_b("OnR");
T_b(rel_numb);
T_b(phrase);
T_b("( null );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(target_type_obj_name);
T_b(" selectAny");
T_b(type_key_letters);
T_b("OnR");
T_b(rel_numb);
T_b(phrase);
T_b("( IWhere condition ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("checkLiving();");
T_b("\n");
if ( is_unconditional ) {
T_b("        ");
T_b("if ( ");
T_b(ref_name);
T_b(".isEmpty() ) throw new ModelIntegrityException( \"Uncoditional association with no related instance.\" );");
T_b("\n");
T_b("        ");
T_b("else return ");
T_b(ref_name);
T_b(".selectAny");
T_b(type_key_letters);
T_b("FromInstances( condition );");
T_b("\n");
} else {
T_b("        ");
T_b("return ");
T_b(ref_name);
T_b(".selectAny");
T_b(type_key_letters);
T_b("FromInstances( condition );");
T_b("\n");
}
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(type_name);
T_b(" selectMany");
T_b(type_key_letters);
T_b("sOnR");
T_b(rel_numb);
T_b(phrase);
T_b("() throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("return selectMany");
T_b(type_key_letters);
T_b("sOnR");
T_b(rel_numb);
T_b(phrase);
T_b("( null );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(type_name);
T_b(" selectMany");
T_b(type_key_letters);
T_b("sOnR");
T_b(rel_numb);
T_b(phrase);
T_b("( IWhere condition ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("checkLiving();");
T_b("\n");
if ( is_unconditional ) {
T_b("        ");
T_b("if ( ");
T_b(ref_name);
T_b(".isEmpty() ) throw new ModelIntegrityException( \"Uncoditional association with no related instance.\" );");
T_b("\n");
T_b("        ");
T_b("else return ");
T_b(ref_name);
T_b(".selectMany");
T_b(type_key_letters);
T_b("sFromInstances( condition );");
T_b("\n");
} else {
T_b("        ");
T_b("return ");
T_b(ref_name);
T_b(".selectMany");
T_b(type_key_letters);
T_b("sFromInstances( condition );");
T_b("\n");
}
T_b("    ");
T_b("}");
T_b("\n");
} else {
T_b("    ");
T_b("public ");
T_b(type_name);
T_b(" selectOne");
T_b(type_key_letters);
T_b("OnR");
T_b(rel_numb);
T_b(phrase);
T_b("() throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("return selectOne");
T_b(type_key_letters);
T_b("OnR");
T_b(rel_numb);
T_b(phrase);
T_b("( null );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("   ");
T_b(" ");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(type_name);
T_b(" selectOne");
T_b(type_key_letters);
T_b("OnR");
T_b(rel_numb);
T_b(phrase);
T_b("( IWhere condition ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("checkLiving();");
T_b("\n");
if ( is_unconditional ) {
T_b("        ");
T_b("if ( ");
T_b(ref_name);
T_b(" instanceof IEmptyInstance ) throw new ModelIntegrityException( \"Uncoditional association with no related instance.\" );");
T_b("\n");
if ( is_subtype ) {
T_b("        ");
T_b("else if ( ");
T_b(ref_name);
T_b(" instanceof ");
T_b(type_name);
T_b(" && ( null == condition || condition.evaluate( ");
T_b(ref_name);
T_b(" ) ) ) return (");
T_b(type_name);
T_b(")");
T_b(ref_name);
T_b(";");
T_b("\n");
} else {
T_b("        ");
T_b("else if ( null == condition || condition.evaluate( ");
T_b(ref_name);
T_b(" ) ) return ");
T_b(ref_name);
T_b(";");
T_b("\n");
}
} else {
T_b("        ");
T_b("if ( null == condition || condition.evaluate( ");
T_b(ref_name);
T_b(" ) ) return ");
T_b(ref_name);
T_b(";");
T_b("\n");
}
T_b("        ");
T_b("else return ");
T_b(type_name);
T_b(".empty");
T_b(type_name);
T_b(";");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
}
