if ( isset ) {
if ( isempty ) {
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(target_type_name);
T_b(" selectMany");
T_b(target_key_letters);
T_b("sOnR");
T_b(rel_numb);
T_b("( Where condition ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("return ");
T_b(target_type_name);
T_b(".empty");
T_b(target_type_name);
T_b(";");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
} else {
T_b("    ");
T_b("public ");
T_b(target_type_name);
T_b(" selectMany");
T_b(target_key_letters);
T_b("sOnR");
T_b(rel_numb);
T_b("() throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("return selectMany");
T_b(target_key_letters);
T_b("sOnR");
T_b(rel_numb);
T_b("( null );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(target_type_name);
T_b(" selectMany");
T_b(target_key_letters);
T_b("sOnR");
T_b(rel_numb);
T_b("( Where condition ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b(target_type_name);
T_b(" return_set = new ");
T_b(target_type_name);
T_b("();");
T_b("\n");
T_b("        ");
T_b("for ( ModelInstance selected : this ) {");
T_b("\n");
if ( is_many ) {
T_b("            ");
T_b("return_set.addAll( ((");
T_b(class_name);
T_b(")selected).selectMany");
T_b(target_key_letters);
T_b("sOnR");
T_b(rel_numb);
T_b("( condition ) );");
T_b("\n");
} else {
T_b("            ");
T_b("return_set.add( ((");
T_b(class_name);
T_b(")selected).selectOne");
T_b(target_key_letters);
T_b("OnR");
T_b(rel_numb);
T_b("( condition ) );");
T_b("\n");
}
T_b("        ");
T_b("}");
T_b("\n");
T_b("        ");
T_b("if ( return_set.isEmpty() ) return ");
T_b(target_type_name);
T_b(".empty");
T_b(target_type_name);
T_b(";");
T_b("\n");
T_b("        ");
T_b("else return return_set;");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
}
} else {
if ( isempty ) {
if ( is_many ) {
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(target_type_name);
T_b(" selectAny");
T_b(target_key_letters);
T_b("OnR");
T_b(rel_numb);
T_b("( Where condition ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("return ");
T_b(target_type_name);
T_b(".empty");
T_b(target_type_name);
T_b(";");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
} else {
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(target_type_name);
T_b(" selectOne");
T_b(target_key_letters);
T_b("OnR");
T_b(rel_numb);
T_b("( Where condition ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("return ");
T_b(target_type_name);
T_b(".empty");
T_b(target_type_name);
T_b(";");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
}
} else {
if ( is_many ) {
T_b("    ");
T_b("public ");
T_b(target_type_name);
T_b(" selectAny");
T_b(target_key_letters);
T_b("OnR");
T_b(rel_numb);
T_b("() throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("return selectAny");
T_b(target_key_letters);
T_b("OnR");
T_b(rel_numb);
T_b("( null );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(target_type_name);
T_b(" selectAny");
T_b(target_key_letters);
T_b("OnR");
T_b(rel_numb);
T_b("( Where condition ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("checkLiving();");
T_b("\n");
if ( is_unconditional ) {
T_b("        ");
T_b("if ( ");
T_b(ref_name);
T_b(" instanceof EmptySet ) throw new ModelIntegrityException( \"Uncoditional association with no related instance.\" );");
T_b("\n");
T_b("        ");
T_b("else return selectAny");
T_b(target_key_letters);
T_b("FromInstances( condition );");
T_b("\n");
} else {
T_b("        ");
T_b("return selectAny");
T_b(target_key_letters);
T_b("sFromInstances( condition );");
T_b("\n");
}
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(target_type_name);
T_b(" selectMany");
T_b(target_key_letters);
T_b("sOnR");
T_b(rel_numb);
T_b("() throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("return selectMany");
T_b(target_key_letters);
T_b("sOnR");
T_b(rel_numb);
T_b("( null );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(target_type_name);
T_b(" selectMany");
T_b(target_key_letters);
T_b("sOnR");
T_b(rel_numb);
T_b("( Where condition ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("checkLiving();");
T_b("\n");
if ( is_unconditional ) {
T_b("        ");
T_b("if ( ");
T_b(ref_name);
T_b(" instanceof EmptySet ) throw new ModelIntegrityException( \"Uncoditional association with no related instance.\" );");
T_b("\n");
T_b("        ");
T_b("else return selectMany");
T_b(target_key_letters);
T_b("sFromInstances( condition );");
T_b("\n");
} else {
T_b("        ");
T_b("return selectMany");
T_b(target_key_letters);
T_b("sFromInstances( condition );");
T_b("\n");
}
T_b("    ");
T_b("}");
T_b("\n");
} else {
T_b("    ");
T_b("public ");
T_b(target_type_name);
T_b(" selectOne");
T_b(target_key_letters);
T_b("OnR");
T_b(rel_numb);
T_b("() throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("return selectOne");
T_b(target_key_letters);
T_b("OnR");
T_b(rel_numb);
T_b("( null );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("   ");
T_b(" ");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(target_type_name);
T_b(" selectOne");
T_b(target_key_letters);
T_b("OnR");
T_b(rel_numb);
T_b("( Where condition ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("checkLiving();");
T_b("\n");
if ( is_unconditional ) {
T_b("        ");
T_b("if ( ");
T_b(ref_name);
T_b(" instanceof EmptyInstance ) throw new ModelIntegrityException( \"Uncoditional association with no related instance.\" );");
T_b("\n");
if ( is_subtype ) {
T_b("        ");
T_b("else if ( ");
T_b(ref_name);
T_b(" instanceof ");
T_b(target_type_name);
T_b(" && ( null == condition || condition.evaluate( ");
T_b(ref_name);
T_b(" ) ) ) return (");
T_b(target_type_name);
T_b(")");
T_b(ref_name);
T_b(";");
T_b("\n");
} else {
T_b("        ");
T_b("else if ( null == condition || condition.evaluate( ");
T_b(ref_name);
T_b(" ) ) return ");
T_b(ref_name);
T_b(";");
T_b("\n");
}
} else {
T_b("        ");
T_b("if ( null == condition || condition.evaluate( ");
T_b(ref_name);
T_b(" ) ) return ");
T_b(ref_name);
T_b(";");
T_b("\n");
}
T_b("        ");
T_b("else return ");
T_b(target_type_name);
T_b(".empty");
T_b(target_type_name);
T_b(";");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
}
}
}
