T_b("package ");
T_b(package_name);
T_b(";");
T_b("\n");
T_b(import_block);
T_b("\n");
T_b("public class ");
T_b(class_set_name);
T_b(" extends InstanceSet {");
T_b("\n");
T_b("    ");
T_b("// empty set");
T_b("\n");
T_b("    ");
T_b("public static final ");
T_b(class_set_name);
T_b(" empty");
T_b(class_set_name);
T_b(" = new Empty");
T_b(class_set_name);
T_b("();");
T_b("\n");
T_b("    ");
T_b("// constructor");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(class_set_name);
T_b("() {");
T_b("\n");
T_b("        ");
T_b("super( ");
T_b(class_name);
T_b(".class );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("// selections");
T_b("\n");
T_b(selections_block);
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(class_name);
T_b(" getEmptyInstance() {");
T_b("\n");
T_b("        ");
T_b("return ");
T_b(class_name);
T_b(".empty");
T_b(class_name);
T_b(";");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("}");
T_b("\n");
T_b("class Empty");
T_b(class_set_name);
T_b(" extends ");
T_b(class_set_name);
T_b(" implements EmptyInstanceSet {");
T_b("\n");
T_b("    ");
T_b("// selections");
T_b("\n");
T_b(empty_selections_block);
T_b("\n");
T_b("}");
T_b("\n");
