T_b("package ");
T_b(package);
T_b(";");
T_b("\n");
T_b(imports);
T_b("\n");
T_b("public class ");
T_b(name);
T_b(" extends ");
T_b(extends);
T_b(" {");
T_b("\n");
T_b("  ");
T_b("// supertype class");
T_b("\n");
T_b("  ");
T_b("private ");
T_b(supertype_class_name);
T_b(" ");
T_b(T_l(supertype_class_name));
T_b(";");
T_b("\n");
T_b("  ");
T_b("// subtype class");
T_b("\n");
T_b("  ");
T_b("private IModelInstance subtype;");
T_b("\n");
T_b("}");
T_b("\n");
