T_b("package ");
T_b(self->package);
T_b(";");
T_b("\n");
T_b(imports);
T_b("\n");
T_b("public class ");
T_b(self->name);
T_b(" extends Port<");
T_b(self->comp_name);
T_b("> implements ");
T_b(self->iface_name);
T_b(" {");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(self->name);
T_b("( ");
T_b(self->comp_name);
T_b(" context, IPort<?> peer ) {");
T_b("\n");
T_b("        ");
T_b("super( context, peer );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("// inbound messages");
T_b("\n");
T_b(inbound_message_block);
T_b("\n");
T_b("    ");
T_b("// outbound messages");
T_b("\n");
T_b(outbound_message_block);
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public void deliver( IMessage message ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("if ( null == message ) throw new BadArgumentException( \"Cannot deliver null message.\" );");
T_b("\n");
T_b("        ");
T_b("switch ( message.getName() ) {");
T_b("\n");
T_b(message_switch_block);
T_b("");
T_b("            ");
T_b("default:");
T_b("\n");
T_b("                ");
T_b("throw new BadArgumentException( \"Message not implemented by this port.\" );");
T_b("\n");
T_b("        ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("}");
T_b("\n");
