T_b("        ");
T_b("if ( !((");
T_b(relationship_set_cast);
T_b(")getRelationshipSet( ");
T_b(rel_num);
T_b(" ) ).getBy");
T_b(T_c(participant));
T_b("Id( ");
T_b(link_parameter_name);
T_b(".getInstanceId() ).isEmpty() ) throw new ModelIntegrityException( \"Cannot relate more than one instance across association.\" );");
T_b("\n");
