T_b("package ");
T_b(self->package);
T_b(";");
T_b("\n");
T_b(imports);
T_b("\n");
T_b("public class ");
T_b(self->name);
T_b(" extends ");
T_b(self->extends);
T_b(" {");
T_b("\n");
T_b("   ");
T_b(" ");
T_b("\n");
T_b("    ");
T_b("private IRunContext runContext;");
T_b("\n");
T_b(instance_extents);
T_b("\n");
T_b("    ");
T_b("public ");
T_b(self->name);
T_b("( IRunContext runContext ) {");
T_b("\n");
T_b("        ");
T_b("this.runContext = runContext;");
T_b("\n");
T_b(instance_extent_initializers);
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("// domain functions");
T_b("\n");
T_b(functions);
T_b("\n");
T_b("    ");
T_b("// creates");
T_b("\n");
T_b(creates);
T_b("\n");
T_b("    ");
T_b("// relates");
T_b("\n");
T_b(relates);
T_b("\n");
T_b("    ");
T_b("// unrelates");
T_b("\n");
T_b(unrelates);
T_b("\n");
T_b("   ");
T_b(" ");
T_b("\n");
T_b("    ");
T_b("// selections");
T_b("\n");
T_b(selectors);
T_b("\n");
T_b("    ");
T_b("// ports");
T_b("\n");
T_b("    ");
T_b("/*");
T_b("\n");
T_b(ports);
T_b("\n");
T_b("    ");
T_b("*/");
T_b("\n");
T_b("    ");
T_b("// component initialization function");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public void initialize() throws XtumlException {");
T_b("\n");
T_b(init);
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public Map<Integer, IRelationshipSet> initializeRelationshipSets() {");
T_b("\n");
T_b("        ");
T_b("Map<Integer, IRelationshipSet> relationships  = new HashMap<>();");
T_b("\n");
T_b(relationship_sets);
T_b("");
T_b("        ");
T_b("return relationships;");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("	  ");
T_b("public IRunContext getRunContext() {");
T_b("\n");
T_b("		    ");
T_b("return runContext;");
T_b("\n");
T_b("	  ");
T_b("}");
T_b("\n");
T_b("	  ");
T_b("@Override");
T_b("\n");
T_b("	  ");
T_b("public ");
T_b(self->name);
T_b(" getPopulationContext() {");
T_b("\n");
T_b("		    ");
T_b("return this;");
T_b("\n");
T_b("	  ");
T_b("}");
T_b("\n");
T_b(relationships);
T_b("\n");
T_b("}");
T_b("\n");
