T_b("package ");
T_b(self->package);
T_b(";");
T_b("\n");
T_b(imports);
T_b("\n");
T_b("public class ");
T_b(self->name);
T_b(" extends ");
T_b(self->extends);
T_b(" {");
T_b("\n");
T_b("   ");
T_b(" ");
T_b("\n");
T_b("    ");
T_b("private IRunContext runContext;");
T_b("\n");
T_b(instance_extents);
T_b("\n");
T_b(relationship_extents);
T_b("\n");
T_b("    ");
T_b("public ");
T_b(self->name);
T_b("( IRunContext runContext ) {");
T_b("\n");
T_b("        ");
T_b("this.runContext = runContext;");
T_b("\n");
T_b(instance_extent_initializers);
T_b("\n");
T_b(relationship_extent_initializers);
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("// domain functions");
T_b("\n");
T_b(functions);
T_b("\n");
T_b("    ");
T_b("// relates and unrelates");
T_b("\n");
T_b(relationship_modifiers);
T_b("\n");
T_b("   ");
T_b(" ");
T_b("\n");
T_b("    ");
T_b("// instance selections");
T_b("\n");
T_b(instance_selectors);
T_b("\n");
T_b("    ");
T_b("// relationship selections");
T_b("\n");
T_b(relationship_selectors);
T_b("\n");
T_b("    ");
T_b("// ports");
T_b("\n");
T_b("    ");
T_b("/*");
T_b("\n");
T_b(ports);
T_b("\n");
T_b("    ");
T_b("*/");
T_b("\n");
T_b("    ");
T_b("// component initialization function");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public void initialize() throws XtumlException {");
T_b("\n");
T_b(init);
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public boolean addInstance( IModelInstance instance ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("if ( null == instance ) throw new BadArgumentException( \"Null instance passed.\" );");
T_b("\n");
T_b("        ");
T_b("if ( instance instanceof IEmptyInstance ) throw new EmptyInstanceException( \"Cannot add empty instance to population.\" );");
T_b("\n");
T_b(instance_adds);
T_b("\n");
T_b("        ");
T_b("return false;");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public boolean removeInstance( IModelInstance instance ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("if ( null == instance ) throw new BadArgumentException( \"Null instance passed.\" );");
T_b("\n");
T_b("        ");
T_b("if ( instance instanceof IEmptyInstance ) throw new EmptyInstanceException( \"Cannot remove empty instance from population.\" );");
T_b("\n");
T_b(instance_removes);
T_b("\n");
T_b("        ");
T_b("return false;");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public IRunContext getRunContext() {");
T_b("\n");
T_b("        ");
T_b("return runContext;");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(self->name);
T_b(" population() {");
T_b("\n");
T_b("        ");
T_b("return this;");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("}");
T_b("\n");
