T_b("        ");
T_b(test);
T_b(" ( ");
T_b(T_s(rel_num));
T_b(" == relNum && ");
T_b(link_parameter_type_check);
T_b(" ) {");
T_b("\n");
T_b("            ");
T_b("if ( !removeRelationship( ((");
T_b(self->relationship_set_cast);
T_b(")getRelationshipSet( ");
T_b(T_s(rel_num));
T_b(" )).getByInstanceIds( ");
T_b(link_parameter_ids);
T_b(" ) ) ) throw new ModelIntegrityException( \"Instances are not related.\" );");
T_b("\n");
T_b("            ");
T_b("// TODO propagate referentials?");
T_b("\n");
T_b("        ");
T_b("}");
T_b("\n");
