T_b("    ");
T_b("public ");
T_b(class_name);
T_b(" ");
T_b(name);
T_b("() throws XtumlException {");
T_b("\n");
T_b("        ");
T_b(class_name);
T_b(" new");
T_b(class_name);
T_b(" = new ");
T_b(class_name);
T_b("( this );");
T_b("\n");
T_b("        ");
T_b("if ( addInstance( new");
T_b(class_name);
T_b(" ) ) return new");
T_b(class_name);
T_b(";");
T_b("\n");
T_b("        ");
T_b("else {");
T_b("\n");
T_b("            ");
T_b("new");
T_b(class_name);
T_b(".delete();");
T_b("\n");
T_b("            ");
T_b("throw new InstancePopulationException( \"Error creating instance of ");
T_b(class_name);
T_b(".\" );");
T_b("\n");
T_b("        ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
