T_b("    ");
T_b("public ");
T_b(self->type_name);
T_b(" ");
T_b(self->name);
T_b("() throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("return (");
T_b(self->type_name);
T_b(")");
T_b(class_extent);
T_b(".toImmutableSet();");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
