T_b("        ");
T_b(test);
T_b(" ( ");
T_b(T_s(rel_num));
T_b(" == relNum && ");
T_b(link_parameter_type_check);
T_b(" ) {");
T_b("\n");
T_b(cardinality_checks);
T_b("            if ( !addRelationship( new ");
T_b(relationship_name);
T_b("( ");
T_b(link_parameter_ids);
T_b(" ) ) ) throw new ModelIntegrityException( \"Instances already related.\" );");
T_b("\n");
T_b("        ");
T_b("}");
T_b("\n");
