T_b("    ");
T_b("public ");
T_b(self->type_name);
T_b(" ");
T_b(self->name);
T_b("() throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("return ");
T_b(self->name);
T_b("( null );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("public ");
T_b(self->type_name);
T_b(" ");
T_b(self->name);
T_b("( IWhere condition ) throws XtumlException {");
T_b("\n");
if ( self->returns_set ) {
T_b("        ");
T_b("if ( null == condition ) return (");
T_b(self->type_name);
T_b(")getInstanceSet( \"");
T_b(self->class_key_letters);
T_b("\" ).toImmutableSet();");
T_b("\n");
T_b("        ");
T_b(self->type_name);
T_b(" ");
T_b(T_l(self->type_name));
T_b(" = new ");
T_b(self->type_name);
T_b("();");
T_b("\n");
}
T_b("        ");
T_b("for ( IModelInstance candidate : getInstanceSet( \"");
T_b(self->class_key_letters);
T_b("\" ) ) {");
T_b("\n");
T_b("            ");
T_b("if ( null == condition || condition.passes( candidate ) ) ");
if ( self->returns_set ) {
T_b(T_l(self->type_name));
T_b(".add( candidate );");
T_b("\n");
T_b("        ");
T_b("}");
T_b("\n");
T_b("        ");
T_b("return (");
T_b(self->type_name);
T_b(")");
T_b(T_l(self->type_name));
T_b(".toImmutableSet();");
T_b("\n");
} else {
T_b("return (");
T_b(self->type_name);
T_b(")candidate;");
T_b("\n");
T_b("        ");
T_b("}");
T_b("\n");
T_b("        ");
T_b("return ");
T_b(self->type_name);
T_b(".EMPTY_");
T_b(T_underscore(T_u(self->type_name)));
T_b(";");
T_b("\n");
}
T_b("    ");
T_b("}");
T_b("\n");
