T_b("    ");
T_b("private IRelationshipSet ");
T_b(self->rel_name);
T_b("_extent;");
T_b("\n");
T_b("    ");
T_b("public IRelationshipSet ");
T_b(self->name);
T_b("() throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("return ");
T_b(self->rel_name);
T_b("_extent.toImmutableSet();");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
