T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public IModelInstance createObjectInstance( String keyLetters ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("switch( keyLetters ) {");
T_b("\n");
T_b(creations);
T_b("            default:");
T_b("\n");
T_b("                ");
T_b("throw new InstancePopulationException( \"Class with key letters '\" + keyLetters + \"' not supported.\" );");
T_b("\n");
T_b("        ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
