T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public void unrelate( int relNum, IModelInstance one, IModelInstance other, IModelInstance link ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("switch( relNum ) {");
T_b("\n");
T_b(associative_unrelates);
T_b("            default:");
T_b("\n");
T_b("                ");
T_b("throw new InstancePopulationException( \"Relationship with number '\" + relNum + \"' not supported.\" );");
T_b("\n");
T_b("        ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("@Override");
T_b("\n");
T_b("    ");
T_b("public void unrelate( int relNum, IModelInstance one, IModelInstance other ) throws XtumlException {");
T_b("\n");
T_b("        ");
T_b("switch( relNum ) {");
T_b("\n");
T_b(other_unrelates);
T_b("            default:");
T_b("\n");
T_b("                ");
T_b("throw new InstancePopulationException( \"Relationship with number '\" + relNum + \"' not supported.\" );");
T_b("\n");
T_b("        ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
